version: "3"
services:
        login-app:
            container_name: url_shortner_api
            image: balajeeasish/url_shortner_api/url_shortner_api
            restart: always
            build: .
            ports:
                - "8080:8080"
            links:
                - mongo
            networks:
                - network
        mongo:
            container_name: mongo
            image: mongo
            volumes:
                - ./data:/data/db
            ports:
                - '27017:27017'
            networks:
                - network
networks:
  network:
    driver: bridge

    